# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Autoload checker

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    name: autoloader
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up php
        uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # v2
        with:
          php-version: 8.1
          tools: composer

      - name: Set up PHPUnit
        working-directory: composer
        run: composer install && composer dump-autoload

      - name: Check difference to committed files
        run: |
          bash -c "[[ ! \"`git status --porcelain -- . ':!composer/composer/installed.php'`\" ]] || exit 1"

      - name: Show changes on failure
        if: failure()
        run: |
          git status
          git --no-pager diff
